- id: pipenv-generate-requirements
  name: Generate requirements.txt
  description: This hook generates a requirements.txt files from Pipfile.lock
  entry: ./generate-reqs.sh
  language: script
  files: ^Pipfile(\.lock)?$

- id: pipenv-generate-requirements-no-index
  name: Generate requirements.txt
  description: This hook generates a requirements.txt files from Pipfile.lock without the index url
  entry: ./generate-reqs-no-index.sh
  language: script
  files: ^Pipfile(\.lock)?$